### ISSUE TITLE
Speed HUD display metric detection not working 

### ISSUE THREAD

**Issue by eappels** [team-stuyk-alt-v/altV-Open-Roleplay#22]
### Describe the bug (What the bug is)
The speed HUD has an option to detect Metric or not through a native.
That doesn't work.
I'm EU and it still shows MPH instead of KMH.

### Reproducing the Bug (Steps)
Resources/orp/client/hud/hud.mjs
Line 60:
isMetric = native.getProfileSetting(227) == 1;
When set it manual after this, it changes to the correct display

### Expected Behavior (How this should be performing)
Show KMH instead of MPH based on region in settings file

### Potential Solution Description (Optional)
Maybe the native is broken or maybe the AltV user needs to change it manualy in the settings file.

**Comment by Stuyk** [comment]
Fixed In: https://github.com/team-stuyk-alt-v/altV-Open-Roleplay/commit/cdaa31b1ff2c66a58737cb8b8621d19454d7ed43
