### ISSUE TITLE
Player out of camera in clothing shop.

### ISSUE THREAD

**Issue by TitoRukas** [team-stuyk-alt-v/altV-Open-Roleplay#4]
If you keep runing when you press "E" in clothing shop the character will be out of the camera, so you won't be able to see the effective changes on the ped.

A possible fix to it will be as easy as calculating camera position when the player is already freezed, and not when it presses "E".

**Comment by Stuyk** [comment]
Fixed in commit https://github.com/team-stuyk-alt-v/altV-Open-Roleplay/commit/5f3e21c9feb737b5eb819000d87cef64dea4afeb
