### ISSUE TITLE
Eyebrow doesn't apply to the character

### ISSUE THREAD

**Issue by mehrangta** [team-stuyk-alt-v/altV-Open-Roleplay#47]
### Reproducing the Bug (Steps)
In character creation menu set eyebrow opacity to 1 and submit

### Expected Behavior (How this should be performing)
It should set the chosen eyebrow to the player

### Potential Solution Description (Optional)
Not sure about this.

**Comment by DooDesch** [comment]
Everything works fine for me, is there anything special you've done?

**Comment by mehrangta** [comment]
Nope, even in Stuyk 's server this happens.
Eyebrow applies to the ped in the character creation, but not to the player when you submit.
