### ISSUE TITLE
Set Roleplay Info

### ISSUE THREAD

**Issue by GalatheasUncharted** [team-stuyk-alt-v/altV-Open-Roleplay#51]
### Describe the bug (What the bug is)
After Character Creation i have to set roleplay info. i typed in my ingame Name like this: Firstname_Lastname like its called in the description.
Enter a birthdate like 09/23/1999 and hit the button Set RP Info.

The Server throws an error:

> [10:46:02][Error] [V8] Exception at orp:file:///D:/GTA5%20Server/altv/resources/orp/server/character/info.mjs:14
>[10:46:02][Error]       var matches = str.match(/(\d+9)/);
>[10:46:02][Error]   ReferenceError: str is not defined
>    at setRoleplayInfo (file:///D:/GTA5%20Server/altv/resources/orp/server/character/info.mjs:14:19)

I checkted the Database, records dosnt save to it..

### Reproducing the Bug (Steps)
1. Close game => Start again => loggin in => same issue
2. Close game => shutdown Server => start Server => start game => loggin in => same issue

### Expected Behavior (How this should be performing)
Store input to Database

**Comment by Stuyk** [comment]
Resolved
